### ISSUE TITLE
[Broken example] ContourAroundPoint

### ISSUE THREAD

**Issue by julien-tierny** [topology-tool-kit/ttk-data#43]
the example ```states/contourAroundPoint.pvsm``` is broken.
it currently looks like this:
![christopher](https://user-images.githubusercontent.com/3018628/86594154-ccc9d380-bf96-11ea-9cf8-586b47772a72.png)
while it should look like that:
https://topology-tool-kit.github.io/img/gallery/contourAroundPoint.jpg

this is a consequence of PR#40.

@kappe-c 
this one is for you.
I suggest to roll back this state file to its previous version (I can roll back PR #40 if it's any easier for you) and only edit (with a text editor) the necessary part of the pvsm state file (see the following example: https://github.com/topology-tool-kit/ttk-data/commit/ba0daada042a2c78dddb0c8700db9639d2791162)

**Comment by kappe-c** [comment]
Hi,
Somehow I didn't think the state would have to match to old one so strictly. I am about to push anew.

**Comment by julien-tierny** [comment]
actually the new example PR (#44) seems still quite different from the old one (https://topology-tool-kit.github.io/img/gallery/contourAroundPoint.jpg). I'll roll back the PR involving that state and suggest to edit the pvsm state file by hand.

**Comment by julien-tierny** [comment]
I've just reverted the two related PRs.
can you please update the pvsm file by just editing the xml file with a text editor?
see this commit for example: https://github.com/topology-tool-kit/ttk-data/commit/ba0daada042a2c78dddb0c8700db9639d2791162

**Comment by kappe-c** [comment]
Honestly, I don't see the difference.
current: 
![contourAroundPoint20200707](https://user-images.githubusercontent.com/20239947/86801180-0b818b80-c074-11ea-9871-70c46f1fdf74.png)
old: 
![contourAroundPoint old](https://user-images.githubusercontent.com/20239947/86801238-176d4d80-c074-11ea-8b23-a40321aa7e33.jpg)

I really would have liked to avoid editing the XML file :-( I dont even want to check what I have changed in my own module since the original state was commited, and there are like five ttk filters upstream that I need, to create the state and I have no idea what might have changed there, and everything twice because of the two included examples.

**Comment by julien-tierny** [comment]
hum, I was getting differences in the bottom left view.
could you open a PR again with that branch such that I give it one more try?

btw: editing the pvsm by hand is the recommended way to go. it seems to be the only way for git to keep track of things (for conflict solving for instance).

**Comment by kappe-c** [comment]
ok. thanks for the patience. I interpreted the "recommended" as in "because it is probably easiest" and i figured for may case a manual reconstruction in the pv gui would be easier, so that's what i did; but when - after all - the text editing is the _only_ way (if only for git) then i shall do this.

**Comment by julien-tierny** [comment]
hi christopher, 

I have edited by hand the pvsm state file to account for the migration to the new api (in particular with SetInputArrayToProcess).
see commit https://github.com/topology-tool-kit/ttk-data/commit/4fe2ed8368179139ac9563808ffc811069d325ae.

however, it looks like I still missed something (see these weird artefacts in the contour, top left):
![christopher](https://user-images.githubusercontent.com/3018628/86898464-07ec1400-c109-11ea-9d3b-73920b903fbb.png)

any other things you changed in the ParaView GUI?
(if not, this may be a deeper bug, at the C++ level).

**Comment by kappe-c** [comment]
Hi, thanks for this! Yes, okay, I think the artifacts are no big problem luckily. I have now added the Tetrahedralize filter after loading the HAPPI data file. It turned out that this file with its rectilinear grid was one of the cases that only worked by chance with TTK. (I am so sorry that I forgot to mention this at the beginning of the discussion but it has become kind of an automatism for me now, so it was out of my head already)

**Comment by kappe-c** [comment]
So to clarify.
original version: no tetrahedralize, yielded the old screenshot back then; now (on your machine at least) shows artifacts (rectangular cells are interpreted as tetrahedra, i assume)
new version: tetrahedralize directly after reader, then use this as input for the persistence diagram etc; yields the screenshot i provided that is basically the old state.

**Comment by julien-tierny** [comment]
alright, we progress.
still some issues though:
![christopher](https://user-images.githubusercontent.com/3018628/86900430-a1b4c080-c10b-11ea-9805-8ef9d19dadd3.png)

error message: 
ERROR: In ../VTK/Common/ExecutionModel/vtkDemandDrivenPipeline.cxx, line 756
vtkPVDataRepresentationPipeline (0x558c3e917140): Input for connection index 0 on input port index 0 for algorithm vtkImageSliceRepresentation(0x558c3e914740) is of type vtkUnstructuredGrid, but a vtkImageData is required.

**Comment by kappe-c** [comment]
Um, this is hard for me to understand too. The problem seems clear: there is an image slice "representation" (vtk parlance vor visualization pipeline element) and these need `vtkImageData` as input (makes sense for easy slicing) but get a `vtkUnstructuredGrid` (which is also not suprising because that is essentially the only dataset type i work with nowadays). 
The strange thing is: I only use representation _surface_ not _image slice_ in all three views.
Maybe in one of the hidden pipeline elements (like the sea-land-mask reader)? But then the error shouldn't really come up if you ask me...

**Comment by julien-tierny** [comment]
alright, I fixed it with a workaround (replacing an instance of TopologicalSimplification by a new one).
looks good now!
